version: '3.8'

services:
  quantum-miner-cuda-q:
    build:
      context: ../..
      dockerfile: cuda_q_quantum_subnet_package/docker/Dockerfile.cuda-q
    image: quantum-miner-cuda-q:latest
    container_name: quantum-miner-cuda-q
    
    # GPU support
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    
    # Volume mounts
    volumes:
      - ../config/default_config.yaml:/app/cuda_q_config.yaml:ro
      - ./logs:/app/logs
      - ./certificates:/app/certificates
      - ./wallets:/app/wallets
    
    # Network configuration
    networks:
      - quantum-subnet
    
    # Restart policy
    restart: unless-stopped
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 32G
        reservations:
          memory: 16G
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    # Health check
    healthcheck:
      test: ["CMD", "python3", "-c", "import cudaq; print('healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  # Optional: Monitoring service
  quantum-monitor:
    image: prom/prometheus:latest
    container_name: quantum-monitor
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - quantum-subnet
    restart: unless-stopped
    profiles:
      - monitoring

  # Optional: Grafana dashboard
  quantum-dashboard:
    image: grafana/grafana:latest
    container_name: quantum-dashboard
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=quantum123
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./monitoring/grafana:/etc/grafana/provisioning:ro
    networks:
      - quantum-subnet
    restart: unless-stopped
    profiles:
      - monitoring

networks:
  quantum-subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  grafana-storage:

